//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.AutoLeasing.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.AutoLeasing.Resources.Admin.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح بالدخول.
        /// </summary>
        public static string Access_denied {
            get {
                return ResourceManager.GetString("Access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك الدخول الي هذه الصفحة.
        /// </summary>
        public static string Access_denied_msg {
            get {
                return ResourceManager.GetString("Access_denied_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الحساب.
        /// </summary>
        public static string AccountTypes {
            get {
                return ResourceManager.GetString("AccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء تفعيل المستخدم !.
        /// </summary>
        public static string ActivateUserErrorMsg {
            get {
                return ResourceManager.GetString("ActivateUserErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل المستخدم بنجاح !.
        /// </summary>
        public static string ActivateUserSuccessMsg {
            get {
                return ResourceManager.GetString("ActivateUserSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جديد.
        /// </summary>
        public static string Addnew {
            get {
                return ResourceManager.GetString("Addnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العودة الي الصفحة الرئيسية.
        /// </summary>
        public static string Back_to_admin {
            get {
                return ResourceManager.GetString("Back_to_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط الاساسي.
        /// </summary>
        public static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم فاتورة بي كير.
        /// </summary>
        public static string BcareInvoiceNumber {
            get {
                return ResourceManager.GetString("BcareInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء ايقاف المستخدم !.
        /// </summary>
        public static string BlockUserErrorMsg {
            get {
                return ResourceManager.GetString("BlockUserErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ايقاف المستخدم بنجاح !.
        /// </summary>
        public static string BlockUserSuccessMsg {
            get {
                return ResourceManager.GetString("BlockUserSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع رقم الهوية.
        /// </summary>
        public static string CardIdTypes {
            get {
                return ResourceManager.GetString("CardIdTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل طلبات الدفع.
        /// </summary>
        public static string CheckoutLog {
            get {
                return ResourceManager.GetString("CheckoutLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات سجل طلبات المدفوعات :.
        /// </summary>
        public static string CheckoutLogDetails {
            get {
                return ResourceManager.GetString("CheckoutLogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المستخدم.
        /// </summary>
        public static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات المطالبات.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المستخدم.
        /// </summary>
        public static string ClientDetails {
            get {
                return ResourceManager.GetString("ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شركه التامين بالعربى.
        /// </summary>
        public static string CompanyArName {
            get {
                return ResourceManager.GetString("CompanyArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شركة التامين بالانجليزية.
        /// </summary>
        public static string CompanyEnName {
            get {
                return ResourceManager.GetString("CompanyEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الشركات.
        /// </summary>
        public static string CompanyTypes {
            get {
                return ResourceManager.GetString("CompanyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل طرق الدفع.
        /// </summary>
        public static string EditpaymentMethod {
            get {
                return ResourceManager.GetString("EditpaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى للعميل.
        /// </summary>
        public static string EmailOfClient {
            get {
                return ResourceManager.GetString("EmailOfClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات طلبات التعديل.
        /// </summary>
        public static string Endorsment {
            get {
                return ResourceManager.GetString("Endorsment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعداد مرفقات طلب التعديل.
        /// </summary>
        public static string EndorsmentAttachmentConfiguration {
            get {
                return ResourceManager.GetString("EndorsmentAttachmentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط طلب التعديل.
        /// </summary>
        public static string EndorsmentUrl {
            get {
                return ResourceManager.GetString("EndorsmentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات إيصال.
        /// </summary>
        public static string EsalConfiguration {
            get {
                return ResourceManager.GetString("EsalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalId.
        /// </summary>
        public static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Premium Price.
        /// </summary>
        public static string ExtraPrice {
            get {
                return ResourceManager.GetString("ExtraPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغير ناجحة.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير المالية.
        /// </summary>
        public static string FinanceReport {
            get {
                return ResourceManager.GetString("FinanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات هايبر بي.
        /// </summary>
        public static string HyperpayConfiguration {
            get {
                return ResourceManager.GetString("HyperpayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال .
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل طلبات الاستعلامات.
        /// </summary>
        public static string InquiryLog {
            get {
                return ResourceManager.GetString("InquiryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات سجل طلبات الإستعلامات :.
        /// </summary>
        public static string InquiryLogDetails {
            get {
                return ResourceManager.GetString("InquiryLogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsuranceCompanyIdRequired.
        /// </summary>
        public static string InsuranceCompanyIdRequired {
            get {
                return ResourceManager.GetString("InsuranceCompanyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsuranceCompanyRequired.
        /// </summary>
        public static string InsuranceCompanyRequired {
            get {
                return ResourceManager.GetString("InsuranceCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المؤمن بالعربى .
        /// </summary>
        public static string InsurredArName {
            get {
                return ResourceManager.GetString("InsurredArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امس المؤمن بالانجليزى.
        /// </summary>
        public static string InsurredEnName {
            get {
                return ResourceManager.GetString("InsurredEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هوية المؤمن.
        /// </summary>
        public static string InsurredNationalId {
            get {
                return ResourceManager.GetString("InsurredNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف المؤمن.
        /// </summary>
        public static string InsurredPhone {
            get {
                return ResourceManager.GetString("InsurredPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الفاتورة.
        /// </summary>
        public static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير النظام.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueDateRequired.
        /// </summary>
        public static string IssueDateRequired {
            get {
                return ResourceManager.GetString("IssueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر وثيقة.
        /// </summary>
        public static string Lastpolicy {
            get {
                return ResourceManager.GetString("Lastpolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر عرض سعر.
        /// </summary>
        public static string LastQuotation {
            get {
                return ResourceManager.GetString("LastQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر رد.
        /// </summary>
        public static string LastResponse {
            get {
                return ResourceManager.GetString("LastResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى للموظفين.
        /// </summary>
        public static string MaxEmployees {
            get {
                return ResourceManager.GetString("MaxEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات الطبية.
        /// </summary>
        public static string MedicalClasses {
            get {
                return ResourceManager.GetString("MedicalClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الافصاح الطبى .
        /// </summary>
        public static string MedicalDeclarations {
            get {
                return ResourceManager.GetString("MedicalDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسباب الحذف.
        /// </summary>
        public static string MedicalDeletionReasons {
            get {
                return ResourceManager.GetString("MedicalDeletionReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الادنى للموظفين.
        /// </summary>
        public static string MinEmployees {
            get {
                return ResourceManager.GetString("MinEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديول.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الانجليزى.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديده.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الدفع.
        /// </summary>
        public static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرق الدفع.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الدفع.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فى انتظار الرد.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات الوثائق.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات ملفات الوثائق.
        /// </summary>
        public static string PolicyAttachments {
            get {
                return ResourceManager.GetString("PolicyAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انشاء الوثيقة.
        /// </summary>
        public static string PolicycreatedDate {
            get {
                return ResourceManager.GetString("PolicycreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEffectiveDateRequired.
        /// </summary>
        public static string PolicyEffectiveDateRequired {
            get {
                return ResourceManager.GetString("PolicyEffectiveDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyExpiryDateRequired.
        /// </summary>
        public static string PolicyExpiryDateRequired {
            get {
                return ResourceManager.GetString("PolicyExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير ملف الوثيقة بنجاح.
        /// </summary>
        public static string PolicyFileUploadedSuccessMsg {
            get {
                return ResourceManager.GetString("PolicyFileUploadedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyNoRequired.
        /// </summary>
        public static string PolicyNoRequired {
            get {
                return ResourceManager.GetString("PolicyNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات CCHI Status.
        /// </summary>
        public static string PolicyUpload {
            get {
                return ResourceManager.GetString("PolicyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع السعر.
        /// </summary>
        public static string PriceTypes {
            get {
                return ResourceManager.GetString("PriceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر .
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التأمين.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصى.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات عروض الاسعار.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل طلبات الاسعار.
        /// </summary>
        public static string QuotationLog {
            get {
                return ResourceManager.GetString("QuotationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات سجل طلبات عروض الأسعار :.
        /// </summary>
        public static string QuotationLogDetails {
            get {
                return ResourceManager.GetString("QuotationLogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceIdRequired.
        /// </summary>
        public static string ReferenceIdRequired {
            get {
                return ResourceManager.GetString("ReferenceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة الدفع.
        /// </summary>
        public static string ReTry {
            get {
                return ResourceManager.GetString("ReTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة تحميل الوثيقة.
        /// </summary>
        public static string ReUploadPolicyFile {
            get {
                return ResourceManager.GetString("ReUploadPolicyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات سداد.
        /// </summary>
        public static string SadadConfiguration {
            get {
                return ResourceManager.GetString("SadadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم آي بي السيرفر.
        /// </summary>
        public static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الطلب.
        /// </summary>
        public static string ServiceRequest {
            get {
                return ResourceManager.GetString("ServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الرد.
        /// </summary>
        public static string ServiceResponse {
            get {
                return ResourceManager.GetString("ServiceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود SMS.
        /// </summary>
        public static string SmsCode {
            get {
                return ResourceManager.GetString("SmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الرسالة.
        /// </summary>
        public static string SmsDescription {
            get {
                return ResourceManager.GetString("SmsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الرسائل.
        /// </summary>
        public static string SmsList {
            get {
                return ResourceManager.GetString("SmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الرسالة.
        /// </summary>
        public static string SmsNumber {
            get {
                return ResourceManager.GetString("SmsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total Price.
        /// </summary>
        public static string SubTotalPrice {
            get {
                return ResourceManager.GetString("SubTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الناجحة.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم القالب.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الصفحة.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الصفحه عربي.
        /// </summary>
        public static string TitleAr {
            get {
                return ResourceManager.GetString("TitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الصفحة انجليزي.
        /// </summary>
        public static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الموظفين الغير سعوديين.
        /// </summary>
        public static string TotalNonSaudi {
            get {
                return ResourceManager.GetString("TotalNonSaudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التابعين الغير سعوديين.
        /// </summary>
        public static string TotalNonSaudiDependent {
            get {
                return ResourceManager.GetString("TotalNonSaudiDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الوثائق.
        /// </summary>
        public static string Totalpolicies {
            get {
                return ResourceManager.GetString("Totalpolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد عروض الاسعار.
        /// </summary>
        public static string TotalQuotations {
            get {
                return ResourceManager.GetString("TotalQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الموظفين  السعوديين.
        /// </summary>
        public static string TotalSaudi {
            get {
                return ResourceManager.GetString("TotalSaudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التابعين السعوديين.
        /// </summary>
        public static string TotalSaudiDependent {
            get {
                return ResourceManager.GetString("TotalSaudiDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التنبيهات.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل الوثيقة.
        /// </summary>
        public static string UploadPolicy {
            get {
                return ResourceManager.GetString("UploadPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتصفح.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم آي بي المستخدم.
        /// </summary>
        public static string UserIP {
            get {
                return ResourceManager.GetString("UserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات المستخدم.
        /// </summary>
        public static string UserPages {
            get {
                return ResourceManager.GetString("UserPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبة القيمة المضتفة.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
    }
}
