//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.AutoLeasing.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.AutoLeasing.Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  رجاء اختيار نوع التغطيه.
        /// </summary>
        public static string AccountTypeRequired {
            get {
                return ResourceManager.GetString("AccountTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الاضافى مطلوب.
        /// </summary>
        public static string AdditionalNumberRequired {
            get {
                return ResourceManager.GetString("AdditionalNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدفع بنجاح.
        /// </summary>
        public static string AlreadyPaid {
            get {
                return ResourceManager.GetString("AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ارجاع الحساب بنجاح.
        /// </summary>
        public static string BalanceSuccess {
            get {
                return ResourceManager.GetString("BalanceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل كود البنك.
        /// </summary>
        public static string BankCodeRequired {
            get {
                return ResourceManager.GetString("BankCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ الميلاد.
        /// </summary>
        public static string BirthDateGRequired {
            get {
                return ResourceManager.GetString("BirthDateGRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ الميلاد الهجرى.
        /// </summary>
        public static string BirthDateHRequired {
            get {
                return ResourceManager.GetString("BirthDateHRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المبنى مطلوب .
        /// </summary>
        public static string BuildingNumberRequired {
            get {
                return ResourceManager.GetString("BuildingNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهويه موجود بالفعل.
        /// </summary>
        public static string Cannotinsertmember {
            get {
                return ResourceManager.GetString("Cannotinsertmember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم البطاقة.
        /// </summary>
        public static string CardNoRequired {
            get {
                return ResourceManager.GetString("CardNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال بريد إلكتروني صحيح.
        /// </summary>
        public static string Checkout_error_email {
            get {
                return ResourceManager.GetString("Checkout_error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال بريد رقم  جوال صحيح.
        /// </summary>
        public static string Checkout_error_phone {
            get {
                return ResourceManager.GetString("Checkout_error_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ال IBAN غير صحيح.
        /// </summary>
        public static string Checkout_InvalidIBAN {
            get {
                return ResourceManager.GetString("Checkout_InvalidIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العرض غير موجود.
        /// </summary>
        public static string Checkout_QuotationRequest_NotExist {
            get {
                return ResourceManager.GetString("Checkout_QuotationRequest_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بوليصة الطلب اقل من  48  ساعة.
        /// </summary>
        public static string Checkout_QuotationRequest_RequestPolicyEffectiveDateIsNotValid {
            get {
                return ResourceManager.GetString("Checkout_QuotationRequest_RequestPolicyEffectiveDateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع غير مكتمل.
        /// </summary>
        public static string Checkout_ReferenceIdIsNull {
            get {
                return ResourceManager.GetString("Checkout_ReferenceIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلة المشريات غير صحيحة.
        /// </summary>
        public static string Checkout_ShippingCartItemIsNotValid {
            get {
                return ResourceManager.GetString("Checkout_ShippingCartItemIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلة المشريات فارغه.
        /// </summary>
        public static string Checkout_ShoppingCartItemIsNull {
            get {
                return ResourceManager.GetString("Checkout_ShoppingCartItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب غير مكتمل.
        /// </summary>
        public static string CheckoutModelIsNullException {
            get {
                return ResourceManager.GetString("CheckoutModelIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينه مطلوب.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل  المبلغ المدفوع.
        /// </summary>
        public static string ClaimAmountRequired {
            get {
                return ResourceManager.GetString("ClaimAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل  رقم الحساب البنكى.
        /// </summary>
        public static string ClaimIBANRequired {
            get {
                return ResourceManager.GetString("ClaimIBANRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود التفعيل غير صحيح.
        /// </summary>
        public static string CodeNotValid {
            get {
                return ResourceManager.GetString("CodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل كود التفعيل.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل  كود البنك.
        /// </summary>
        public static string CompanyBankCoderequired {
            get {
                return ResourceManager.GetString("CompanyBankCoderequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السجل التجارى غير صحيح.
        /// </summary>
        public static string CompanyCrnumber_invalid {
            get {
                return ResourceManager.GetString("CompanyCrnumber_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجارى يجب ان يكون 10 ارقام.
        /// </summary>
        public static string CompanyCRNumberLengthError {
            get {
                return ResourceManager.GetString("CompanyCRNumberLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال السجل التجارى.
        /// </summary>
        public static string CompanyCrnumberRequired {
            get {
                return ResourceManager.GetString("CompanyCrnumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل رقم حساب صحيح.
        /// </summary>
        public static string CompanyIbanInvalid {
            get {
                return ResourceManager.GetString("CompanyIbanInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل رقم الحساب.
        /// </summary>
        public static string CompanyIbanRequired {
            get {
                return ResourceManager.GetString("CompanyIbanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم يجب ان يكون باللغة الانجليزية.
        /// </summary>
        public static string CompanyName_invalid {
            get {
                return ResourceManager.GetString("CompanyName_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشركة لا يقبل حروف عربى او ارقام .
        /// </summary>
        public static string CompanyNameEnMustbeEnglish {
            get {
                return ResourceManager.GetString("CompanyNameEnMustbeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم الشركة.
        /// </summary>
        public static string CompanyNameEnRequired {
            get {
                return ResourceManager.GetString("CompanyNameEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم الشركة.
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد شركه بهذا الرقم.
        /// </summary>
        public static string CompanyNotExists {
            get {
                return ResourceManager.GetString("CompanyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحاسب غير صحيح.
        /// </summary>
        public static string CompanySponsor_invalid {
            get {
                return ResourceManager.GetString("CompanySponsor_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحاسب الالى يجب ان يكون 10 ارقام.
        /// </summary>
        public static string CompanySponsorIdLengthError {
            get {
                return ResourceManager.GetString("CompanySponsorIdLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الضريبى غير صحيح.
        /// </summary>
        public static string CompanyVatNumber_invalid {
            get {
                return ResourceManager.GetString("CompanyVatNumber_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال.
        /// </summary>
        public static string CompanyVatNumberRequired {
            get {
                return ResourceManager.GetString("CompanyVatNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى موجود بالفعل برجاء تأكيد البريد الالكترونى.
        /// </summary>
        public static string ConfirmemailMsg {
            get {
                return ResourceManager.GetString("ConfirmemailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تأكيد البريد الالكتروني.
        /// </summary>
        public static string ConfirmEmailRequired {
            get {
                return ResourceManager.GetString("ConfirmEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .تم ارسال كود التفعيل على رقم الهاتف الخاص بك برجاء تأكيد رقم الهاتف.
        /// </summary>
        public static string ConfirmEmailSuccess {
            get {
                return ResourceManager.GetString("ConfirmEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز المميز غير صالح..
        /// </summary>
        public static string ConfirmEmailTokenInvalid {
            get {
                return ResourceManager.GetString("ConfirmEmailTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد انتهت صلاحية طلبك للانضمام إلى البرنامج..
        /// </summary>
        public static string ConfirmJoinProgramRequestExpired {
            get {
                return ResourceManager.GetString("ConfirmJoinProgramRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .تم تأكيد انضمامك بنجاح.
        /// </summary>
        public static string ConfirmJoinProgramSuccess {
            get {
                return ResourceManager.GetString("ConfirmJoinProgramSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز المميز غير صالح..
        /// </summary>
        public static string ConfirmJoinProgramTokenInvalid {
            get {
                return ResourceManager.GetString("ConfirmJoinProgramTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور مطلوب.
        /// </summary>
        public static string ConfirmPassword_required {
            get {
                return ResourceManager.GetString("ConfirmPassword_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تأكيد كلمة السر.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال سبب التصحيح.
        /// </summary>
        public static string CorrectionReasonCodeRequired {
            get {
                return ResourceManager.GetString("CorrectionReasonCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السجل التجارى غير صحيح.
        /// </summary>
        public static string CrNumberInvalid {
            get {
                return ResourceManager.GetString("CrNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجارى يجب ان يكون ارقام.
        /// </summary>
        public static string CRNumberMustbeonlyNumber {
            get {
                return ResourceManager.GetString("CRNumberMustbeonlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السجل التجارى غير موجود .
        /// </summary>
        public static string CrNumberNotExist {
            get {
                return ResourceManager.GetString("CrNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجارى موجود بالفعل.
        /// </summary>
        public static string crnumberRepeated {
            get {
                return ResourceManager.GetString("crnumberRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء حفظ البيانات اولا.
        /// </summary>
        public static string CurrentMemberEditMsg {
            get {
                return ResourceManager.GetString("CurrentMemberEditMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد يجب ان يكون اقل من تاريخ اليوم.
        /// </summary>
        public static string DateRangeErrorMsg {
            get {
                return ResourceManager.GetString("DateRangeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند حذف هذا الموظف سيتم حذف كل التابعين له . هل تريد الاستمرار ؟.
        /// </summary>
        public static string DeleteDependenciesAlarm {
            get {
                return ResourceManager.GetString("DeleteDependenciesAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل  سبب المسح.
        /// </summary>
        public static string DeletionReasonCodeRequired {
            get {
                return ResourceManager.GetString("DeletionReasonCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم حذف هذا العضو. هل تريد الاستمرار ؟.
        /// </summary>
        public static string DeletMemberAlarm {
            get {
                return ResourceManager.GetString("DeletMemberAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء إلغاء تسجيل دخولك من البرنامج ، يرجى المحاولة مرة أخرى..
        /// </summary>
        public static string DisenrollUserErrorHappen {
            get {
                return ResourceManager.GetString("DisenrollUserErrorHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المقاطعة مطلوب.
        /// </summary>
        public static string DistrictRequired {
            get {
                return ResourceManager.GetString("DistrictRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني موجود بالفعل.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم موجود بالفعل.
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء اختيار تاريخ التفعيل.
        /// </summary>
        public static string EffectiveDateRequired {
            get {
                return ResourceManager.GetString("EffectiveDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى غير صحيح.
        /// </summary>
        public static string Email_invalid {
            get {
                return ResourceManager.GetString("Email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الايميل مستخدم من قبل شخص اخر..
        /// </summary>
        public static string EmailAlreadyUsedByAnotherUser {
            get {
                return ResourceManager.GetString("EmailAlreadyUsedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية هذا الرابط.
        /// </summary>
        public static string EmailExpired {
            get {
                return ResourceManager.GetString("EmailExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  رجاء ادخال بريد الكترونى صحيح.
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال بريد الكترونى صحيح.
        /// </summary>
        public static string Emailnotvalid {
            get {
                return ResourceManager.GetString("Emailnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال البريد الالكترونى.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملفات فارغه.
        /// </summary>
        public static string EmptyFiles {
            get {
                return ResourceManager.GetString("EmptyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsment Service response error is :.
        /// </summary>
        public static string EndorsementServiceResError {
            get {
                return ResourceManager.GetString("EndorsementServiceResError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عمليه ارسال الطلب بنجاح.
        /// </summary>
        public static string EndorseSuccess {
            get {
                return ResourceManager.GetString("EndorseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال المرفق.
        /// </summary>
        public static string EndorsmentFileRequired {
            get {
                return ResourceManager.GetString("EndorsmentFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون الملف من نوع xlsx.
        /// </summary>
        public static string ExcelFileTypeError {
            get {
                return ResourceManager.GetString("ExcelFileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على نتائج.
        /// </summary>
        public static string FailedToFetchData {
            get {
                return ResourceManager.GetString("FailedToFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء حفظ بيانات المستخدم , برجاء المحاولة مره اخرى .
        /// </summary>
        public static string FailedToSaveUser {
            get {
                return ResourceManager.GetString("FailedToSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى انشاء طلب xml.
        /// </summary>
        public static string FailGenerateXML {
            get {
                return ResourceManager.GetString("FailGenerateXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل ارسال الميل.
        /// </summary>
        public static string FailSendingMail {
            get {
                return ResourceManager.GetString("FailSendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف غير موجود.
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاءاختر الملف.
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ForgetEmailHeader {
            get {
                return ResourceManager.GetString("ForgetEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الاسم بالكامل.
        /// </summary>
        public static string FullNameEnRequired {
            get {
                return ResourceManager.GetString("FullNameEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الجنس.
        /// </summary>
        public static string genderCodeRequired {
            get {
                return ResourceManager.GetString("genderCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ ميلادى صحيح.
        /// </summary>
        public static string GeorganDateErrorMsg {
            get {
                return ResourceManager.GetString("GeorganDateErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ هجرى.
        /// </summary>
        public static string HigriDate {
            get {
                return ResourceManager.GetString("HigriDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ هجرى صحيح.
        /// </summary>
        public static string HijriDateErrorMsg {
            get {
                return ResourceManager.GetString("HijriDateErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل ال IBAN.
        /// </summary>
        public static string IbanRequired {
            get {
                return ResourceManager.GetString("IbanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات غير مكتمله.
        /// </summary>
        public static string IncompleteData {
            get {
                return ResourceManager.GetString("IncompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركه التأمين غير موجوده.
        /// </summary>
        public static string InsurranceCompanyNotFound {
            get {
                return ResourceManager.GetString("InsurranceCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم بطاقة صحيح.
        /// </summary>
        public static string InvalidCardNumber {
            get {
                return ResourceManager.GetString("InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغه غير مسموح بها .
        /// </summary>
        public static string InValidCulture {
            get {
                return ResourceManager.GetString("InValidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي إدخال بيانات صحيحة.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنسيق البريد الالكترونى غير صحيح.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد طلب اخر على هذا العضو.
        /// </summary>
        public static string InvalidEndorsement {
            get {
                return ResourceManager.GetString("InvalidEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ فى الدفع.
        /// </summary>
        public static string InvalidPayment {
            get {
                return ResourceManager.GetString("InvalidPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم غير صحيح.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الضريبى يجب ان يكون 15 رقم.
        /// </summary>
        public static string InvalidVatNumber {
            get {
                return ResourceManager.GetString("InvalidVatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاتورة غير موجودة.
        /// </summary>
        public static string InvoiceIsNull {
            get {
                return ResourceManager.GetString("InvoiceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاقامه فارغ.
        /// </summary>
        public static string IqamaNull {
            get {
                return ResourceManager.GetString("IqamaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ارسال ايميل الاشتراك فى البرنامج.
        /// </summary>
        public static string JoinProgramMailSent {
            get {
                return ResourceManager.GetString("JoinProgramMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني او كلمة السر غير صحيحة.
        /// </summary>
        public static string LoginNotCorrect {
            get {
                return ResourceManager.GetString("LoginNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء تاكيد البريد الالكترونى .
        /// </summary>
        public static string MailNotConfirmed {
            get {
                return ResourceManager.GetString("MailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف موجود بالفعل .
        /// </summary>
        public static string MemberAlreadyExist {
            get {
                return ResourceManager.GetString("MemberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف موجود فى الوثيقة الحالية.
        /// </summary>
        public static string MemberAlreadyExist1 {
            get {
                return ResourceManager.GetString("MemberAlreadyExist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الفئة الطبية.
        /// </summary>
        public static string MemberClassCodeRequired {
            get {
                return ResourceManager.GetString("MemberClassCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء التاكد من عدد الافراد المراد التأمين عليهم
        ///يجب ان يكون عدد اعضاء الوثيقة كما هو مسجل في التأمينات الاجتماعية.
        /// </summary>
        public static string MemberCountErrorMsg {
            get {
                return ResourceManager.GetString("MemberCountErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال بيانات العمالة المنزلية لديكم.
        /// </summary>
        public static string MemberCountErrorMsg1 {
            get {
                return ResourceManager.GetString("MemberCountErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال بيانات الافراد المقيمين و كفيلهم.
        /// </summary>
        public static string MemberCountErrorMsg2 {
            get {
                return ResourceManager.GetString("MemberCountErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف موجود بالفعل .
        /// </summary>
        public static string MemberExistinlist {
            get {
                return ResourceManager.GetString("MemberExistinlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف غير موجود فى الشركة.
        /// </summary>
        public static string MemberExistnotinlist {
            get {
                return ResourceManager.GetString("MemberExistnotinlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم صحيح.
        /// </summary>
        public static string MemberFullName {
            get {
                return ResourceManager.GetString("MemberFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الطول.
        /// </summary>
        public static string MemberheightReq {
            get {
                return ResourceManager.GetString("MemberheightReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ الميلاد هجرى.
        /// </summary>
        public static string MemberhijriBirthDateRequired {
            get {
                return ResourceManager.GetString("MemberhijriBirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم هوية صحيح.
        /// </summary>
        public static string MemberId_invalid {
            get {
                return ResourceManager.GetString("MemberId_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل  تاريخ انتهاء رقم الهويه.
        /// </summary>
        public static string MemberIdDateRequired {
            get {
                return ResourceManager.GetString("MemberIdDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ انتهاء رقم الهوية.
        /// </summary>
        public static string MemberIdExpiryDateRequired {
            get {
                return ResourceManager.GetString("MemberIdExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم الهوية.
        /// </summary>
        public static string MemberIdRequired {
            get {
                return ResourceManager.GetString("MemberIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم الهوية صحيح.
        /// </summary>
        public static string MemberNewId_invalid {
            get {
                return ResourceManager.GetString("MemberNewId_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم الهوية الجديد.
        /// </summary>
        public static string MemberNewIdRequired {
            get {
                return ResourceManager.GetString("MemberNewIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الوظيفة.
        /// </summary>
        public static string MemberOccupationCodeRequired {
            get {
                return ResourceManager.GetString("MemberOccupationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال العلاقة.
        /// </summary>
        public static string MemberRelationRequired {
            get {
                return ResourceManager.GetString("MemberRelationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال موظفين اولاً.
        /// </summary>
        public static string MembersIsEmpty {
            get {
                return ResourceManager.GetString("MembersIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الوزن.
        /// </summary>
        public static string MemberWeightReq {
            get {
                return ResourceManager.GetString("MemberWeightReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود التفعيل الخاص بك هو .
        /// </summary>
        public static string MessageBody {
            get {
                return ResourceManager.GetString("MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية يجب ان لا يقل عن 10 ارقام.
        /// </summary>
        public static string MinlengthErrormsg {
            get {
                return ResourceManager.GetString("MinlengthErrormsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم رقم الجوال.
        /// </summary>
        public static string MobileNumberRequired {
            get {
                return ResourceManager.GetString("MobileNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم الهاتف.
        /// </summary>
        public static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان البريدى غير صحيح.
        /// </summary>
        public static string NationalAddress_invalid {
            get {
                return ResourceManager.GetString("NationalAddress_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال العنوان البريدى.
        /// </summary>
        public static string NationalAddressRequired {
            get {
                return ResourceManager.GetString("NationalAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الجنسية.
        /// </summary>
        public static string NationalityCodeRequired {
            get {
                return ResourceManager.GetString("NationalityCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم فارغ.
        /// </summary>
        public static string NInIsNull {
            get {
                return ResourceManager.GetString("NInIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك وثيقة تأمين حاليا.
        /// </summary>
        public static string NoActivePolicyfound {
            get {
                return ResourceManager.GetString("NoActivePolicyfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لا يمكن تقليل فئة هذا العضو لانه على اقل فئة طبية فى هذه البوليصه.
        /// </summary>
        public static string NoDown {
            get {
                return ResourceManager.GetString("NoDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لن يتم تعديل رقم الهاتف .
        /// </summary>
        public static string NoMobileUpdated {
            get {
                return ResourceManager.GetString("NoMobileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موجود.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نأسف، المحتوى الذي تبحث عنه غير متوفر. من الممكن أن يكون هناك تهجئة خاطئة، أو أنك قمت بالنقر على رابط غير متوفر حالياَ. تأكد من الأمر، أو عد إلى الصفحة الرئيسية.
        /// </summary>
        public static string Notfound_description {
            get {
                return ResourceManager.GetString("Notfound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عُـذرًا قد تم حذف الملف أو إلغاؤه.
        /// </summary>
        public static string Notfound_title {
            get {
                return ResourceManager.GetString("Notfound_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير ناجح.
        /// </summary>
        public static string NotSuccess {
            get {
                return ResourceManager.GetString("NotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ModelState is not Valid.
        /// </summary>
        public static string NotValidModelState {
            get {
                return ResourceManager.GetString("NotValidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تطوير هذا العضو لانه على اعلى فئة طبية فى هذه البوليصه.
        /// </summary>
        public static string NoUpgrade {
            get {
                return ResourceManager.GetString("NoUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب فارغ.
        /// </summary>
        public static string NullEsalRequest {
            get {
                return ResourceManager.GetString("NullEsalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم فارغ.
        /// </summary>
        public static string NullUserId {
            get {
                return ResourceManager.GetString("NullUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال  نوع الوظيفة.
        /// </summary>
        public static string occupationTypeRequired {
            get {
                return ResourceManager.GetString("occupationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية مطلوبة.
        /// </summary>
        public static string Oldpassword_required {
            get {
                return ResourceManager.GetString("Oldpassword_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال كلمة السر الحاليه.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية كلمة المرور. قم بتسجيل الدخول مرة أخرى.
        /// </summary>
        public static string OneTimePasswordExpired {
            get {
                return ResourceManager.GetString("OneTimePasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء إرسال كلمة السر أحادية الاستخدام. من فضلك جرّب فى وقت لاحق..
        /// </summary>
        public static string OneTimePasswordSendFailedMsg {
            get {
                return ResourceManager.GetString("OneTimePasswordSendFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستصلك رسالة قصيرة تحتوى على كلمة مرور أحادية الاستخدام..
        /// </summary>
        public static string OneTimePasswordSendSuccessMsg {
            get {
                return ResourceManager.GetString("OneTimePasswordSendSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه الوثيقة تحتوى على فئه طبية  واحده.
        /// </summary>
        public static string OnlyOneClass {
            get {
                return ResourceManager.GetString("OnlyOneClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغير كلمة السر برجاء المحاولة مرة اخرى.
        /// </summary>
        public static string PasswordNotChanged {
            get {
                return ResourceManager.GetString("PasswordNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال كلمة السر.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر وتاكيد كلمة السر غير متطابقان.
        /// </summary>
        public static string PasswordsNotMatches {
            get {
                return ResourceManager.GetString("PasswordsNotMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان لا تقل عن 6 حروف او ارقام.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم المرجع او رقم الفاتورة.
        /// </summary>
        public static string PaymentScreenErrorMsg {
            get {
                return ResourceManager.GetString("PaymentScreenErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تكرار رقم الهاتف.
        /// </summary>
        public static string Phone_number_exist {
            get {
                return ResourceManager.GetString("Phone_number_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم جوال صحيح.
        /// </summary>
        public static string Phone_number_invalid {
            get {
                return ResourceManager.GetString("Phone_number_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم هاتف صحيح.
        /// </summary>
        public static string PhoneFormatError {
            get {
                return ResourceManager.GetString("PhoneFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال تاريخ الميلاد.
        /// </summary>
        public static string PleaseEnterBirthDate {
            get {
                return ResourceManager.GetString("PleaseEnterBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاءادخال تاريخ صحيح.
        /// </summary>
        public static string PleaseEnterValidBirthDate {
            get {
                return ResourceManager.GetString("PleaseEnterValidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية التامين غير صحيح.
        /// </summary>
        public static string PolicyEffectiveDateNotValid {
            get {
                return ResourceManager.GetString("PolicyEffectiveDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية التامين مطلوب.
        /// </summary>
        public static string PolicyEffectiveDateRequired {
            get {
                return ResourceManager.GetString("PolicyEffectiveDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البوليصه فارغ.
        /// </summary>
        public static string PolicyError1 {
            get {
                return ResourceManager.GetString("PolicyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع فارغ.
        /// </summary>
        public static string PolicyError2 {
            get {
                return ResourceManager.GetString("PolicyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمه البوليصه تعودبخطأ وهو.
        /// </summary>
        public static string PolicyError3 {
            get {
                return ResourceManager.GetString("PolicyError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize the returned value which is :.
        /// </summary>
        public static string PolicyError4 {
            get {
                return ResourceManager.GetString("PolicyError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicySchedule Service response error is :.
        /// </summary>
        public static string PolicyError5 {
            get {
                return ResourceManager.GetString("PolicyError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملف عائد من الشركه.
        /// </summary>
        public static string PolicyError6 {
            get {
                return ResourceManager.GetString("PolicyError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل اصدار ملف البوليسه.
        /// </summary>
        public static string PolicyFileGeneraionFailure {
            get {
                return ResourceManager.GetString("PolicyFileGeneraionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ارسال طلب  البوليصه بنجاح.
        /// </summary>
        public static string PolicyRequsetSent {
            get {
                return ResourceManager.GetString("PolicyRequsetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم البريدى مطلوب.
        /// </summary>
        public static string PostCodeRequired {
            get {
                return ResourceManager.GetString("PostCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المنتج غير موجود.
        /// </summary>
        public static string ProductsIsNull {
            get {
                return ResourceManager.GetString("ProductsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductsRequired.
        /// </summary>
        public static string ProductsRequired {
            get {
                return ResourceManager.GetString("ProductsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عروض خصومات.
        /// </summary>
        public static string PromotionError1 {
            get {
                return ResourceManager.GetString("PromotionError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث عروض الخصومات.
        /// </summary>
        public static string PromotionError2 {
            get {
                return ResourceManager.GetString("PromotionError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى تحديث عروض الخصومات.
        /// </summary>
        public static string PromotionError3 {
            get {
                return ResourceManager.GetString("PromotionError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ تفعيل عرض الخصم يجب ان يكون اكبر من تاريخ عدم التفعيل.
        /// </summary>
        public static string PromotionError4 {
            get {
                return ResourceManager.GetString("PromotionError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون معرف برنامج الترويج أقل من 1.
        /// </summary>
        public static string PromotionIdError {
            get {
                return ResourceManager.GetString("PromotionIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotationDateRequired.
        /// </summary>
        public static string QuotationDateRequired {
            get {
                return ResourceManager.GetString("QuotationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انتهاء صلاحية المنتج.
        /// </summary>
        public static string QuotationExpired {
            get {
                return ResourceManager.GetString("QuotationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotationExpiryDateRequired.
        /// </summary>
        public static string QuotationExpiryDateRequired {
            get {
                return ResourceManager.GetString("QuotationExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية هذا المنتج.
        /// </summary>
        public static string QuotationisExpiried {
            get {
                return ResourceManager.GetString("QuotationisExpiried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotationNoRequired.
        /// </summary>
        public static string QuotationNoRequired {
            get {
                return ResourceManager.GetString("QuotationNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ارسال طلب العروض بنجاح.
        /// </summary>
        public static string QutationRequsetSent {
            get {
                return ResourceManager.GetString("QutationRequsetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع غير مكتمل.
        /// </summary>
        public static string ReferenceIdRequired {
            get {
                return ResourceManager.GetString("ReferenceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود التفعيل الخاص بك هو :.
        /// </summary>
        public static string RegisterSmsHeader {
            get {
                return ResourceManager.GetString("RegisterSmsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال يوجد عند مستخدم أخر.
        /// </summary>
        public static string RepeatedMobile {
            get {
                return ResourceManager.GetString("RepeatedMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تكرار رقم الكفيل.
        /// </summary>
        public static string RepeatedSponsorId {
            get {
                return ResourceManager.GetString("RepeatedSponsorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرد فارغ.
        /// </summary>
        public static string ResponseEmpty {
            get {
                return ResourceManager.GetString("ResponseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الرد.
        /// </summary>
        public static string ResponseFail {
            get {
                return ResourceManager.GetString("ResponseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض غير موجود برحاء المحاولة فى وقت اخر.
        /// </summary>
        public static string ResponseNotFound {
            get {
                return ResourceManager.GetString("ResponseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر الرد.
        /// </summary>
        public static string ResponsePending {
            get {
                return ResourceManager.GetString("ResponsePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء حفظ البيانات برجاء المحاولة مرة اخرى .
        /// </summary>
        public static string SaveErrorMsg {
            get {
                return ResourceManager.GetString("SaveErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما برجاء حاول مرة اخرى.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوى الخدمه تعود بفارغ.
        /// </summary>
        public static string ServiceContentNull {
            get {
                return ResourceManager.GetString("ServiceContentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوى عائد الخدمه يعود بفارغ.
        /// </summary>
        public static string ServiceContentResultNull {
            get {
                return ResourceManager.GetString("ServiceContentResultNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمه تعود بفارغ.
        /// </summary>
        public static string ServiceNull {
            get {
                return ResourceManager.GetString("ServiceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء ارسال الرساله.
        /// </summary>
        public static string SmsNotSentSuccessfullly {
            get {
                return ResourceManager.GetString("SmsNotSentSuccessfullly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ارسال الرساله بنجاح.
        /// </summary>
        public static string SmsSentSuccessfullly {
            get {
                return ResourceManager.GetString("SmsSentSuccessfullly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال ألحالة الاجتماعية.
        /// </summary>
        public static string socialStatusCodeRequired {
            get {
                return ResourceManager.GetString("socialStatusCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم الكفيل.
        /// </summary>
        public static string SponserFullNameRequired {
            get {
                return ResourceManager.GetString("SponserFullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال رقم كفيل صحيح.
        /// </summary>
        public static string SponsorId_invalid {
            get {
                return ResourceManager.GetString("SponsorId_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحاسب الالى يجب ان يكون ارقام.
        /// </summary>
        public static string SponsorIdMustbeonlyNumber {
            get {
                return ResourceManager.GetString("SponsorIdMustbeonlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحاسب موجود بالفعل.
        /// </summary>
        public static string SponsorIdRepeated {
            get {
                return ResourceManager.GetString("SponsorIdRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخل  رقم الحاسب.
        /// </summary>
        public static string SponsorIdRequired {
            get {
                return ResourceManager.GetString("SponsorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء اختيار الكفيل.
        /// </summary>
        public static string SponsorRequired {
            get {
                return ResourceManager.GetString("SponsorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشارع مطلوب.
        /// </summary>
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البريد الالكترونى يوجد مسبقا.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنحاج.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا النطاق غير فعال.
        /// </summary>
        public static string thisdomainnotactive {
            get {
                return ResourceManager.GetString("thisdomainnotactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق مطلوب.
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال نوع رقم الهوية.
        /// </summary>
        public static string TypeCodeRequired {
            get {
                return ResourceManager.GetString("TypeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Issuance.
        /// </summary>
        public static string UnderIssuance {
            get {
                return ResourceManager.GetString("UnderIssuance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوحدة مطلوب.
        /// </summary>
        public static string UnitNumberRequired {
            get {
                return ResourceManager.GetString("UnitNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يطابق نطاقك نطاقات برنامج الترويج هذا.
        /// </summary>
        public static string UserDomianDosntExistInProgramDomains {
            get {
                return ResourceManager.GetString("UserDomianDosntExistInProgramDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id Not Found.
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير مفعل.
        /// </summary>
        public static string UserIsBlocked {
            get {
                return ResourceManager.GetString("UserIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على هذا المستخدم برجاءقم بتسجيل الدخول مره اخرى.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط التفعيل غير صحيح.
        /// </summary>
        public static string VerifyEmailCodeError {
            get {
                return ResourceManager.GetString("VerifyEmailCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على بيانات فى علم برجاء مراجعة البيانات المدخلة.
        /// </summary>
        public static string YakeenFailedMsg {
            get {
                return ResourceManager.GetString("YakeenFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عناوين لهذه الشركة.
        /// </summary>
        public static string ZeroAddresses {
            get {
                return ResourceManager.GetString("ZeroAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد نتائج.
        /// </summary>
        public static string ZeroSearchResults {
            get {
                return ResourceManager.GetString("ZeroSearchResults", resourceCulture);
            }
        }
    }
}
