//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tameenk.AutoLeasing.Resources.PrivacyPolicy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivacyPolicy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tameenk.AutoLeasing.Resources.PrivacyPolicy.PrivacyPolicy", typeof(PrivacyPolicy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصول إلى معلوماتك الشخصية.
        /// </summary>
        public static string Accessing {
            get {
                return ResourceManager.GetString("Accessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكنك فحص أو تنقيح معلوماتك الشخصية عبر الإنترنت. وللمساعدة على منع فحص معلوماتك الشخصية أو الإطلاع من قبل أشخاص آخرين، سيطلب منك التوقيع وبيان أوراق اعتمادك.
        /// </summary>
        public static string Accessing_body {
            get {
                return ResourceManager.GetString("Accessing_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجراء تغييرات على بيان والخصوصية هذا.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنقوم من حين لآخر بتحديث هذا البيان ليعكس التغييرات التي تجرى في خدماتنا واستجابة العملاء. وعندما ننشر تغييرات على هذا البيان، نقوم بتعديل \&quot;أخر تحديث\&quot; للتاريخ أعلى هذا البيان. ونحثك على مراجعة هذا البيان لتطلع على الكيفية التي تقوم بها عناية الوسيط بحماية معلوماتك..
        /// </summary>
        public static string Changes_body {
            get {
                return ResourceManager.GetString("Changes_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفات الكوكيز.
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكوكيز عبارة عن معلومة يتم تخزينها على القرص الصلب بجهاز الكمبيوتر بواسطة جهاز خادم ويب لتحسين وتبسيط خبرة مستخدم أي موقع ويب من خلال تحديد هوية المستخدم إذا قام مسبقًا بالدخول إلى ذلك الموقع. ويتم في العادة استخدام ملفات الكوكيز على الإنترنت ولا يمكن أن تضر جهاز الكمبيوتر الخاص بالمستخدم. ملفات الكوكيز المستخدمة في الموقع لا تشمل أي معلومات يمكن أن يقرأها أو يفهمها آخرون عنك، مثل اسمك أو أي رقم حساب أو رقم وثيقة تأمين. وهي لا تحتوي على أي معلومات شخصية عنك. معظم برامج تصفح الإنترنت تسمح لك بإغلاق وظيفة ال [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Cookies_body {
            get {
                return ResourceManager.GetString("Cookies_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنطبق هذه الشروط والأحكام على استخدامك للموقع الإلكتروني الموجود على موقع تأمينك..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنفيذ بيان الخصوصية هذا.
        /// </summary>
        public static string Enforcement {
            get {
                return ResourceManager.GetString("Enforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إن كانت لديك أية استفسارات بخصوص هذا البيان، عليك أن تتصل بنا ..
        /// </summary>
        public static string Enforcement_body {
            get {
                return ResourceManager.GetString("Enforcement_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات الأمنية الخاصة بمعلوماتك الشخصية.
        /// </summary>
        public static string Securing {
            get {
                return ResourceManager.GetString("Securing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلتزم عناية الوسيط بحماية أمن معلوماتك الشخصية وتستخدم مختلف التقنيات والإجراءات الأمنية لحماية معلوماتك الشخصية ضد الوصول غير المصرح به أو استخدام معلوماتك الشخصية أو كشفها من قبل الآخرين. على سبيل المثال، عندما نرسل معلومات ذات درجة عالية من السرية عبر الإنترنت (كأرقام البطاقات الائتمانية أو كلمات السر) نقوم بحمايتها عن طريق استخدام التشفير، مثل نظام طبقة المقبس الأمني (SSL). وفي حالة استخدام كلمة السر للمساعدة على حماية حساباتك ومعلوماتك الشخصية، فإنه من صميم مسؤولياتك المحافظة على سرية كلمة السر الخاصة  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Securing_body {
            get {
                return ResourceManager.GetString("Securing_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيـان التدابير الأمنية الوقائية والخصوصية.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلتزم شركة عناية الوسيط بحماية خصوصيتك. ينطبق بيان عناية الوسيط المتعلق بالخصوصية عبر الإنترنت على البيانات التي تجمعها من خلال الدخول على هذه الخدمة المباشرة المقدمة عبر الإنترنت ..
        /// </summary>
        public static string Security_body {
            get {
                return ResourceManager.GetString("Security_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزيع معلوماتك الشخصية.
        /// </summary>
        public static string Sharing {
            get {
                return ResourceManager.GetString("Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باستثناء ما يوصف في هذا البيان، لن نقوم بكشف أو إفشاء معلوماتك الشخصية إلى شخص آخر بخلاف عناية الوسيط. ويجوز لنا كشف معلوماتك الشخصية إذا كنا نعتقد بأن هذا الإجراء يعتبر ضرورياً من أجل: (أ) التقيد والامتثال بأحكام القانون أو بالإجراءات القانونية؛ (ب) حماية حقوق أو ممتلكات عناية الوسيط والدفاع عنها (بما في ذلك تنفيذ اتفاقياتنا)؛ أو (ج) التصرف في الظروف العاجلة لحماية السلامة الشخصية لعملاء عناية الوسيط أو منسوبيها أو الجمهور..
        /// </summary>
        public static string Sharing_body {
            get {
                return ResourceManager.GetString("Sharing_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام معلوماتك الشخصية.
        /// </summary>
        public static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقوم عناية الوسيط بجمع واستخدام معلوماتك الشخصية لتنفيذ المعاملات التي طلبتها ولتشغيل وتحسين موقعها. وقد تشمل هذه الاستخدامات تزويدك بخدمة العملاء الأكثر فعالية وجعل الخدمات أكثر سهولة للاستخدام بإزالة الحاجة لتكرار إدخال نفس المعلومات وإجراء البحوث والدراسات التي تهدف لتحسين وتطوير منتجاتنا وخدماتنا. كما أننا نستخدم معلوماتك الشخصية للتواصل معك. وقد نرسل لك بعض الرسائل كخطابات الترحيب والتذكير المتعلق بالفواتير والمعلومات ذات الصلة بعقود التأمين الخاصة بك بالإضافة إلى مواد العروض والمنتجات. وربما نرسل لك م [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Using_body {
            get {
                return ResourceManager.GetString("Using_body", resourceCulture);
            }
        }
    }
}
